name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ https://gist.github.com/sujin7837/ }}
          TIMEZONE: Asia/Seoul
